# Generated by Django 5.0.1 on 2024-06-09 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.SmallIntegerField(unique=True)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.SmallIntegerField(unique=True)),
                ('floor', models.CharField(choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.SmallIntegerField()),
                ('month', models.CharField(max_length=42)),
                ('mess_days', models.SmallIntegerField()),
                ('mess_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.SmallIntegerField()),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgm_id', models.SmallIntegerField(unique=True)),
                ('pgm_name', models.CharField(max_length=100, unique=True)),
                ('no_of_sems', models.PositiveSmallIntegerField()),
                ('grad_level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=5)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admn_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('year_of_admn', models.PositiveSmallIntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be a 10-digit number.', regex='^\\d{10}$')])),
                ('house_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_occupation', models.CharField(max_length=100)),
                ('annual_income', models.PositiveIntegerField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('OEC', 'OEC'), ('SC', 'SC'), ('ST', 'ST')], default='GENERAL', max_length=20)),
                ('E_Grantz', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('pgm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.messbill')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'unique_together': {('name', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.attendancedate')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'unique_together': {('date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('year', models.SmallIntegerField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.messbill')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'unique_together': {('name', 'month', 'year')},
            },
        ),
    ]
