# Generated by Django 5.0.6 on 2024-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='grad_level',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('IPG', 'IPG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('Ground', 'Ground'), ('First', 'First')], max_length=50),
        ),
    ]
