# Generated by Django 5.0.6 on 2025-08-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='grad_level',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='no_of_sems',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='pgm_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_admn',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='year_of_admn',
        ),
    ]
