# Generated by Django 5.0.6 on 2024-06-23 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_continuousabsence_month_alter_messbill_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_exited',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admn_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('year_of_admn', models.PositiveSmallIntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be a 10-digit number.', regex='^\\d{10}$')])),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_occupation', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('annual_income', models.PositiveIntegerField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_exited', models.DateField(blank=True, null=True)),
                ('room_no', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('OEC', 'OEC'), ('SC', 'SC'), ('ST', 'ST')], default='GENERAL', max_length=20)),
                ('E_Grantz', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('pgm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.programme')),
            ],
        ),
    ]
