# Generated by Django 5.0.6 on 2024-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_student_date_exited_remove_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')]),
        ),
        migrations.AlterField(
            model_name='trash',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
