# Generated by Django 5.0.6 on 2024-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedate',
            name='month',
            field=models.CharField(default='June', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancedate',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
