# Generated by Django 5.0.6 on 2024-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_remove_student_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='room_no',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
